"""No user-visible AI surface may reveal which model/vendor powers it.

Two layers, both tested here:
  1. PROMPT — every conversational surface's system prompt carries an identity
     guardrail instructing the model to answer only as "Rilono AI".
  2. SCRUB — every surface's output passes through ai_guardrails.
     sanitize_provider_disclosures (via the two legacy sanitizer wrappers), which
     rewrites the leaks the model still produces. The canonical regression is the
     reply observed in production: "I am a large language model, trained by Google."

Run: python -m pytest tests/test_ai_identity_guardrails.py
"""

import re
from pathlib import Path
from types import SimpleNamespace

import pytest

from app.ai_guardrails import sanitize_provider_disclosures

WEB_APP = Path(__file__).resolve().parents[1]

# Words that must never survive in a sanitized AI reply (case-insensitive).
FORBIDDEN = re.compile(
    r"gemini|deepmind|vertex\s*ai|chatgpt|openai|gpt-|large\s+language\s+model|by\s+google",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Layer 2 — the shared scrubber
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("leak", [
    "I am a large language model, trained by Google.",           # the production leak
    "I'm a large language model developed by Google DeepMind.",
    "I am Gemini, an AI made by Google.",
    "This answer was generated by gemini-2.5-flash via Vertex AI.",
    "I'm powered by Google Generative AI (Google AI Studio).",
    "No, I'm not ChatGPT — I'm a model created by OpenAI.",      # cross-vendor echo
    "As a large language model I cannot do that.",
])
def test_scrubber_removes_provider_identity(leak):
    cleaned = sanitize_provider_disclosures(leak)
    assert not FORBIDDEN.search(cleaned), f"{leak!r} → {cleaned!r} still leaks"


def test_production_leak_reads_naturally():
    cleaned = sanitize_provider_disclosures("I am a large language model, trained by Google.")
    assert cleaned == "I am an AI assistant, built by Rilono."


def test_scrubber_preserves_legitimate_content():
    for text in [
        "The lead came in through Google Ads last week.",         # CRM lead source
        "Search Google for the university's official deadline page.",
        "Priya moved 3 clients to the documents stage.",
        "Client Claude Martin is at the interview stage.",        # human named Claude
    ]:
        assert sanitize_provider_disclosures(text) == text


def test_scrubber_handles_empty():
    assert sanitize_provider_disclosures("") == ""
    assert sanitize_provider_disclosures(None) == ""


def test_legacy_wrappers_delegate_to_shared_scrubber():
    from app.enterprise_ai import sanitize_public_ai_text
    from app.routers.ai_chat import sanitize_ai_response_for_public_display
    leak = "I am a large language model, trained by Google."
    expected = "I am an AI assistant, built by Rilono."
    assert sanitize_public_ai_text(leak) == expected
    assert sanitize_ai_response_for_public_display(leak) == expected


# ---------------------------------------------------------------------------
# Layer 1 — prompt guardrails per surface
# ---------------------------------------------------------------------------

def test_enterprise_dashboard_assistant_prompt_has_identity_guardrail():
    from app import enterprise_ai
    system = enterprise_ai._system_instruction("Test Org", "Test User", "admin")
    assert "Identity guardrail" in system
    assert "Rilono AI" in system


def test_extension_copilot_prompts_have_identity_guardrail():
    from app import enterprise_copilot
    org = SimpleNamespace(company_name="Test Org")
    staff = SimpleNamespace(full_name="Staff Person", email="s@example.com")
    client = SimpleNamespace(
        full_name="Client Person", destination_country_name="Canada",
        destination_country_code="CA", visa_type="Study Permit",
    )
    staff_prompt = enterprise_copilot.build_system_prompt(
        organization=org, staff_user=staff, role="admin", client=client,
        profile_block="-", documents_block="-", journey_block="",
    )
    client_prompt = enterprise_copilot.build_client_system_prompt(
        organization=org, client=client,
        profile_block="-", documents_block="-", journey_block="",
    )
    for prompt in (staff_prompt, client_prompt):
        assert "Identity guardrail" in prompt
        assert "do not mention Gemini, Google" in prompt


@pytest.mark.parametrize("relpath", [
    "app/routers/ai_chat.py",       # B2C chat + B2C visa-prep interview mode
    "app/university_shortlist.py",
    "app/course_catalog.py",        # Course Finder AI shortlist
    "app/sop_kit.py",
])
def test_other_ai_surfaces_keep_their_identity_guardrail(relpath):
    source = (WEB_APP / relpath).read_text(encoding="utf-8")
    assert "Identity guardrail" in source, f"{relpath} lost its identity guardrail"


def test_interview_officer_never_admits_being_ai():
    # The mock-interview officer is guarded differently — it must stay in character
    # and never say it is an AI at all; its replies also pass the shared scrubber.
    source = (WEB_APP / "app" / "enterprise_interview.py").read_text(encoding="utf-8")
    # The instruction spans two adjacent string literals in the source.
    assert "Never say you" in source and "are an AI" in source
    assert "sanitize_public_ai_text" in source


def test_daily_notifications_scrub_user_visible_text():
    source = (WEB_APP / "app" / "services" / "daily_ai_notifications.py").read_text(encoding="utf-8")
    assert "sanitize_provider_disclosures" in source
