"""Canonical country-of-residence list shared by B2C signup and onboarding.

One list, one normalizer: the signup and onboarding dropdowns in static/app.js embed the
SAME names (tests/test_residence_country.py keeps the two in sync), and the endpoints
accept nothing outside it. Until 2026-08-24 the signup select offered only the 9 pricing
countries and pre-selected "United States" (the Google-signup path even hardcoded it), so
"home country" was a default, not a fact — and the AI surfaces reasoned from it.
"""

RESIDENCE_COUNTRIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Democratic Republic)",
    "Congo (Republic)",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

# Shown first in the dropdowns (the audience is overwhelmingly study-abroad students).
POPULAR_RESIDENCE_COUNTRIES = ["India", "Nigeria", "Pakistan", "Bangladesh", "Nepal", "Sri Lanka", "China", "Vietnam", "Philippines", "United Arab Emirates", "United States", "United Kingdom"]

_CANONICAL = {c.lower(): c for c in RESIDENCE_COUNTRIES}
_ALIASES = {
    "usa": "United States", "us": "United States", "united states of america": "United States",
    "america": "United States", "uk": "United Kingdom", "great britain": "United Kingdom",
    "britain": "United Kingdom", "england": "United Kingdom", "uae": "United Arab Emirates",
    "korea": "South Korea", "republic of korea": "South Korea", "czechia": "Czech Republic",
    "ivory coast": "Cote d'Ivoire", "burma": "Myanmar", "holland": "Netherlands",
    "drc": "Congo (Democratic Republic)", "russian federation": "Russia", "türkiye": "Turkey",
    "turkiye": "Turkey", "viet nam": "Vietnam", "cape verde": "Cabo Verde",
}


def normalize_residence_country(value, *, required: bool = True):
    """Return the canonical country name, or None for blank optional input.
    Raises ValueError with the user-facing message otherwise."""
    text = " ".join(str(value or "").split())
    if not text:
        if required:
            raise ValueError("Select your current country of residence.")
        return None
    hit = _CANONICAL.get(text.lower()) or _ALIASES.get(text.lower())
    if not hit:
        raise ValueError("Pick your country of residence from the list.")
    return hit
