"""
Rilono Enterprise AI assistant.

A Gemini function-calling agent that answers consultancy staff questions about
their own portal ("how many got approved this week?", "who needs my attention?",
"what's the status of Rohan?"). The model is given a set of READ-ONLY tools, each
hard-scoped to the caller's organization_id, so:

  * Tenant isolation is guaranteed — a tool can only ever read the caller's org.
  * Access is read-only by construction — tools only run SELECTs; no writes,
    no raw SQL generated by the model.
  * Answers are accurate — counts/aggregations come from the database, not the LLM.

Reuses the existing Gemini setup in app.utils.gemini_service.

NOTE: this module intentionally does NOT use `from __future__ import annotations`.
The Gemini SDK introspects the tool function signatures at runtime to build their
schemas, which requires real (non-stringized) type annotations.
"""

import hashlib
import json
import logging
import os
import re
from datetime import datetime, timedelta, date
from typing import Optional

from sqlalchemy import func, or_
from sqlalchemy.orm import Session

from app import models
from app import ai_usage
from app import enterprise_catalog as catalog
from app.utils import gemini_service as gemini_utils

logger = logging.getLogger(__name__)

MAX_HISTORY_TURNS = 12

INTERNAL_PROVIDER_DISCLOSURE_PATTERN = re.compile(
    r"\b(?:gemini[-\w.]*|google\s+generative\s+ai|google\s+genai|vertex\s+ai)\b",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Availability
# ---------------------------------------------------------------------------

def is_ai_configured() -> bool:
    """True when a usable Gemini API key is present for the standard SDK path."""
    key = (gemini_utils.GEMINI_API_KEY or "").strip()
    return bool(gemini_utils.GENAI_AVAILABLE and key and key.startswith("AIza"))


def sanitize_public_ai_text(text: str) -> str:
    """Keep internal provider/model names out of user-visible assistant text."""
    value = str(text or "").strip()
    if not value:
        return value
    return INTERNAL_PROVIDER_DISCLOSURE_PATTERN.sub("Rilono AI", value)


def _enterprise_model_candidates() -> list[str]:
    return gemini_utils.get_model_candidates(
        primary_env="ENTERPRISE_AI_MODEL",
        candidates_env="ENTERPRISE_AI_MODEL_CANDIDATES",
    )


# ---------------------------------------------------------------------------
# Normalizers (map natural language to canonical values)
# ---------------------------------------------------------------------------

_STATUS_SYNONYMS = {
    "lead": catalog.STAGE_NEW_LEAD, "leads": catalog.STAGE_NEW_LEAD, "new": catalog.STAGE_NEW_LEAD,
    "new lead": catalog.STAGE_NEW_LEAD, "enquiry": catalog.STAGE_NEW_LEAD, "inquiry": catalog.STAGE_NEW_LEAD,
    "documents": catalog.STAGE_DOCUMENTS, "document": catalog.STAGE_DOCUMENTS, "collecting": catalog.STAGE_DOCUMENTS,
    "docs": catalog.STAGE_DOCUMENTS,
    "submitted": catalog.STAGE_SUBMITTED, "application submitted": catalog.STAGE_SUBMITTED, "filed": catalog.STAGE_SUBMITTED,
    "appointment": catalog.STAGE_APPOINTMENT, "biometrics": catalog.STAGE_APPOINTMENT, "interview": catalog.STAGE_APPOINTMENT,
    "vfs": catalog.STAGE_APPOINTMENT,
    "decision": catalog.STAGE_DECISION, "awaiting decision": catalog.STAGE_DECISION, "awaiting": catalog.STAGE_DECISION,
    "under review": catalog.STAGE_DECISION, "pending": catalog.STAGE_DECISION,
    "approved": catalog.STAGE_APPROVED, "approval": catalog.STAGE_APPROVED, "granted": catalog.STAGE_APPROVED,
    "rejected": catalog.STAGE_REJECTED, "refused": catalog.STAGE_REJECTED, "denied": catalog.STAGE_REJECTED,
    "on hold": catalog.STAGE_ON_HOLD, "hold": catalog.STAGE_ON_HOLD, "paused": catalog.STAGE_ON_HOLD,
}


def _normalize_status(value: Optional[str]) -> Optional[str]:
    v = str(value or "").strip().lower()
    if not v:
        return None
    if v in catalog.CLIENT_STAGE_KEYS:
        return v
    return _STATUS_SYNONYMS.get(v)


def _normalize_country(value: Optional[str]) -> Optional[str]:
    """Accept a 2-letter code or a country name, return the canonical code."""
    v = str(value or "").strip()
    if not v:
        return None
    if v.upper() in catalog.COUNTRY_CODES:
        return v.upper()
    vl = v.lower()
    for c in catalog.COUNTRIES:
        if c["name"].lower() == vl or c["name"].lower().startswith(vl) or vl in c["name"].lower():
            return c["code"]
    return None


def _period_range(period: Optional[str]) -> tuple[Optional[datetime], Optional[datetime]]:
    """Return (start, end) datetimes for a friendly period label."""
    p = str(period or "").strip().lower().replace("-", "_").replace(" ", "_")
    now = datetime.utcnow()
    start_today = now.replace(hour=0, minute=0, second=0, microsecond=0)
    if p in ("today",):
        return start_today, None
    if p in ("yesterday",):
        return start_today - timedelta(days=1), start_today
    if p in ("this_week", "week", "last_7_days", "last_week", "7_days", "past_week"):
        return now - timedelta(days=7), None
    if p in ("this_month", "month", "last_30_days", "last_month", "30_days", "past_month"):
        return now - timedelta(days=30), None
    if p in ("all", "ever", "all_time", ""):
        return None, None
    return None, None


# ---------------------------------------------------------------------------
# Serialization helpers
# ---------------------------------------------------------------------------

def _stage_label(status_key: str) -> str:
    stage = catalog.CLIENT_STAGE_MAP.get(status_key)
    return stage["label"] if stage else status_key


def _iso(value) -> Optional[str]:
    if value is None:
        return None
    try:
        return value.isoformat()
    except Exception:
        return str(value)


def _client_brief(c: models.EnterpriseClient, member_names: dict | None = None) -> dict:
    assigned = None
    if c.assigned_to_user_id and member_names:
        assigned = member_names.get(int(c.assigned_to_user_id))
    return {
        "id": c.id,
        "name": c.full_name,
        "status": _stage_label(c.status),
        "destination": c.destination_country_name,
        "visa_type": c.visa_type,
        "intake": c.intake,
        "priority": c.priority,
        "key_date": _iso(c.target_date),
        "assigned_to": assigned,
        "email": c.email,
        "phone": c.phone,
    }


# ---------------------------------------------------------------------------
# Tool factory — every tool is a closure bound to (db, organization_id)
# ---------------------------------------------------------------------------

def build_org_tools(db: Session, organization_id: int) -> list:
    org_id = int(organization_id)

    def _member_names() -> dict:
        rows = (
            db.query(models.EnterpriseOrganizationMember.user_id, models.User.full_name, models.User.email)
            .join(models.User, models.User.id == models.EnterpriseOrganizationMember.user_id)
            .filter(
                models.EnterpriseOrganizationMember.organization_id == org_id,
                models.EnterpriseOrganizationMember.is_active.is_(True),
            )
            .all()
        )
        return {int(uid): (full or email or "Team member") for uid, full, email in rows}

    def _base():
        return db.query(models.EnterpriseClient).filter(models.EnterpriseClient.organization_id == org_id)

    def get_portal_overview() -> dict:
        """Get a high-level overview of the entire portal: total clients, a breakdown
        by pipeline stage, by visa type, by destination country, how many are approved
        vs rejected, and how many new clients were added this week and this month.
        Use this for broad 'how is my portal doing' style questions."""
        total = _base().count()
        by_status = {k: 0 for k in catalog.CLIENT_STAGE_KEYS}
        for s, n in (_base().with_entities(models.EnterpriseClient.status, func.count(models.EnterpriseClient.id))
                     .group_by(models.EnterpriseClient.status).all()):
            if s in by_status:
                by_status[s] = int(n)
        status_labelled = {_stage_label(k): v for k, v in by_status.items() if v}
        by_country = {}
        for code, n in (_base().with_entities(models.EnterpriseClient.destination_country_name, func.count(models.EnterpriseClient.id))
                        .group_by(models.EnterpriseClient.destination_country_name).all()):
            by_country[code] = int(n)
        by_visa = {}
        for vt, n in (_base().with_entities(models.EnterpriseClient.visa_type, func.count(models.EnterpriseClient.id))
                      .group_by(models.EnterpriseClient.visa_type).all()):
            by_visa[vt] = int(n)
        week_start, _ = _period_range("this_week")
        month_start, _ = _period_range("this_month")
        new_week = _base().filter(models.EnterpriseClient.created_at >= week_start).count()
        new_month = _base().filter(models.EnterpriseClient.created_at >= month_start).count()
        return {
            "total_clients": total,
            "by_status": status_labelled,
            "by_destination_country": by_country,
            "by_visa_type": by_visa,
            "new_clients_last_7_days": new_week,
            "new_clients_last_30_days": new_month,
        }

    def count_clients(
        status: Optional[str] = None,
        destination_country: Optional[str] = None,
        visa_type: Optional[str] = None,
        added_period: Optional[str] = None,
        updated_period: Optional[str] = None,
    ) -> dict:
        """Count clients matching optional filters.
        - status: a pipeline stage such as 'approved', 'rejected', 'submitted',
          'documents', 'interview', 'awaiting decision', 'new lead', 'on hold'.
        - destination_country: country name or 2-letter code (US, CA, UK, AU, DE, IE).
        - visa_type: a substring of the visa type (e.g. 'F-1', 'Study Permit').
        - added_period: filter by when the client was ADDED. One of 'today',
          'yesterday', 'this_week', 'this_month', 'all'.
        - updated_period: filter by when the client's record last CHANGED (a good
          proxy for status changes). Same options as added_period. For example, to
          answer 'how many were approved today', use status='approved' and
          updated_period='today'.
        Returns the matching count and the filters that were applied."""
        q = _base()
        applied = {}
        st = _normalize_status(status)
        if status and st:
            q = q.filter(models.EnterpriseClient.status == st)
            applied["status"] = _stage_label(st)
        code = _normalize_country(destination_country)
        if destination_country and code:
            q = q.filter(models.EnterpriseClient.destination_country_code == code)
            applied["destination_country"] = catalog.COUNTRY_MAP[code]["name"]
        if visa_type:
            q = q.filter(func.lower(models.EnterpriseClient.visa_type).like(f"%{visa_type.strip().lower()}%"))
            applied["visa_type"] = visa_type
        if added_period:
            s, e = _period_range(added_period)
            if s is not None:
                q = q.filter(models.EnterpriseClient.created_at >= s)
            if e is not None:
                q = q.filter(models.EnterpriseClient.created_at < e)
            applied["added_period"] = added_period
        if updated_period:
            s, e = _period_range(updated_period)
            if s is not None:
                q = q.filter(models.EnterpriseClient.updated_at >= s)
            if e is not None:
                q = q.filter(models.EnterpriseClient.updated_at < e)
            applied["updated_period"] = updated_period
        return {"count": int(q.count()), "filters_applied": applied or "none"}

    def search_clients(
        query: Optional[str] = None,
        status: Optional[str] = None,
        destination_country: Optional[str] = None,
        limit: int = 20,
    ) -> dict:
        """Search for clients and return a short list with their key fields.
        - query: matches name, email, phone, passport number or application reference.
        - status: optional pipeline stage filter.
        - destination_country: optional country name or code.
        - limit: max results (default 20, capped at 50).
        Use this to list clients matching a description."""
        q = _base()
        st = _normalize_status(status)
        if status and st:
            q = q.filter(models.EnterpriseClient.status == st)
        code = _normalize_country(destination_country)
        if destination_country and code:
            q = q.filter(models.EnterpriseClient.destination_country_code == code)
        if query and query.strip():
            like = f"%{query.strip().lower()}%"
            q = q.filter(or_(
                func.lower(models.EnterpriseClient.full_name).like(like),
                func.lower(models.EnterpriseClient.email).like(like),
                func.lower(models.EnterpriseClient.phone).like(like),
                # passport_number is encrypted at rest and not substring-searchable.
                func.lower(models.EnterpriseClient.application_reference).like(like),
            ))
        n = max(1, min(int(limit or 20), 50))
        rows = q.order_by(models.EnterpriseClient.created_at.desc()).limit(n).all()
        names = _member_names()
        return {"count": len(rows), "clients": [_client_brief(c, names) for c in rows]}

    def get_client_details(name: Optional[str] = None, client_id: Optional[int] = None) -> dict:
        """Get the full profile for a single client, including contact info, passport,
        visa case, status, assigned counselor, key date, and the most recent notes on
        their file. Provide either the client's name or their client_id. If multiple
        clients match a name, a list of candidates is returned instead."""
        q = _base()
        if client_id:
            client = q.filter(models.EnterpriseClient.id == int(client_id)).first()
        elif name and name.strip():
            matches = q.filter(func.lower(models.EnterpriseClient.full_name).like(f"%{name.strip().lower()}%")).limit(10).all()
            if len(matches) > 1:
                names = _member_names()
                return {"multiple_matches": [_client_brief(c, names) for c in matches]}
            client = matches[0] if matches else None
        else:
            return {"error": "Provide a client name or client_id."}
        if not client:
            return {"error": "No matching client found."}
        names = _member_names()
        notes = (
            db.query(models.EnterpriseClientNote)
            .filter(models.EnterpriseClientNote.client_id == client.id)
            .order_by(models.EnterpriseClientNote.created_at.desc())
            .limit(8).all()
        )
        detail = _client_brief(client, names)
        detail.update({
            "nationality": client.nationality,
            "passport_number": client.passport_number,
            "passport_expiry": _iso(client.passport_expiry),
            "application_reference": client.application_reference,
            "added_on": _iso(client.created_at),
            "last_updated": _iso(client.updated_at),
            "recent_notes": [
                {"by": nt.author_name, "on": _iso(nt.created_at), "note": nt.body} for nt in notes
            ],
        })
        return detail

    def clients_needing_attention(limit: int = 15) -> dict:
        """List clients that likely need staff attention right now, each with a reason.
        Flags: key date overdue or within 14 days while still in an early stage, high or
        urgent priority, on hold, new leads untouched for over 7 days, and missing
        contact details. Results are ranked most-urgent first. Use this for
        'who needs my attention' / 'what should I follow up on' questions."""
        today = date.today()
        names = _member_names()
        open_early = {catalog.STAGE_NEW_LEAD, catalog.STAGE_DOCUMENTS}
        terminal = {catalog.STAGE_APPROVED, catalog.STAGE_REJECTED}
        rows = _base().filter(models.EnterpriseClient.status.notin_(list(terminal))).all()
        scored = []
        now = datetime.utcnow()
        for c in rows:
            reasons = []
            score = 0
            td = c.target_date
            if td:
                days = (td - today).days
                if days < 0:
                    reasons.append(f"Key date passed {abs(days)} day(s) ago"); score += 100 + abs(days)
                elif days <= 14 and c.status in open_early:
                    reasons.append(f"Key date in {days} day(s) but still {_stage_label(c.status).lower()}"); score += 80 - days
                elif days <= 7:
                    reasons.append(f"Key date in {days} day(s)"); score += 40 - days
            if c.priority in ("urgent", "high"):
                reasons.append(f"Marked {c.priority} priority"); score += 50 if c.priority == "urgent" else 30
            if c.status == catalog.STAGE_ON_HOLD:
                reasons.append("On hold"); score += 20
            if c.status == catalog.STAGE_NEW_LEAD and c.created_at:
                created = c.created_at.replace(tzinfo=None) if getattr(c.created_at, "tzinfo", None) else c.created_at
                age = (now - created).days
                if age >= 7:
                    reasons.append(f"New lead untouched for {age} day(s)"); score += 15 + age
            if not (c.email or "").strip() and not (c.phone or "").strip():
                reasons.append("No contact details on file"); score += 10
            if reasons:
                item = _client_brief(c, names)
                item["reasons"] = reasons
                scored.append((score, item))
        scored.sort(key=lambda x: x[0], reverse=True)
        n = max(1, min(int(limit or 15), 40))
        return {"count": len(scored), "clients": [it for _, it in scored[:n]]}

    def list_recent_activity(within_days: int = 7) -> dict:
        """Show recent activity: clients added and notes written within the last N days
        (default 7). Use for 'what's happened recently' / 'any updates this week'."""
        days = max(1, min(int(within_days or 7), 90))
        cutoff = datetime.utcnow() - timedelta(days=days)
        names = _member_names()
        added = _base().filter(models.EnterpriseClient.created_at >= cutoff).order_by(models.EnterpriseClient.created_at.desc()).limit(25).all()
        notes = (
            db.query(models.EnterpriseClientNote, models.EnterpriseClient.full_name)
            .join(models.EnterpriseClient, models.EnterpriseClient.id == models.EnterpriseClientNote.client_id)
            .filter(models.EnterpriseClientNote.organization_id == org_id, models.EnterpriseClientNote.created_at >= cutoff)
            .order_by(models.EnterpriseClientNote.created_at.desc()).limit(25).all()
        )
        return {
            "window_days": days,
            "clients_added": [_client_brief(c, names) for c in added],
            "notes_added": [
                {"client": cname, "by": nt.author_name, "on": _iso(nt.created_at), "note": nt.body}
                for nt, cname in notes
            ],
        }

    def get_team_workload() -> dict:
        """List team members and how many active (non-closed) clients are assigned to
        each, plus how many clients are currently unassigned. Use for workload questions."""
        names = _member_names()
        terminal = [catalog.STAGE_APPROVED, catalog.STAGE_REJECTED]
        counts = dict(
            _base().filter(models.EnterpriseClient.status.notin_(terminal),
                           models.EnterpriseClient.assigned_to_user_id.isnot(None))
            .with_entities(models.EnterpriseClient.assigned_to_user_id, func.count(models.EnterpriseClient.id))
            .group_by(models.EnterpriseClient.assigned_to_user_id).all()
        )
        unassigned = _base().filter(models.EnterpriseClient.status.notin_(terminal),
                                    models.EnterpriseClient.assigned_to_user_id.is_(None)).count()
        workload = [{"member": names.get(int(uid), "Unknown"), "active_clients": int(n)} for uid, n in counts.items()]
        workload.sort(key=lambda x: x["active_clients"], reverse=True)
        return {"team": workload, "unassigned_active_clients": unassigned}

    def _resolve_client_row(name=None, client_id=None):
        q = _base()
        if client_id:
            return q.filter(models.EnterpriseClient.id == int(client_id)).first(), None
        if name and str(name).strip():
            matches = q.filter(func.lower(models.EnterpriseClient.full_name).like(f"%{str(name).strip().lower()}%")).limit(10).all()
            if len(matches) > 1:
                return None, matches
            return (matches[0] if matches else None), None
        return None, None

    def list_client_documents(name: Optional[str] = None, client_id: Optional[int] = None) -> dict:
        """List the documents uploaded for a client (document type, file name, who
        uploaded it and when). Provide the client's name or client_id. Use this for
        'what documents do we have for X' / 'has X uploaded their passport' questions."""
        client, multi = _resolve_client_row(name, client_id)
        if multi:
            return {"multiple_matches": [_client_brief(c) for c in multi]}
        if not client:
            return {"error": "No matching client found."}
        rows = (
            db.query(models.EnterpriseClientDocument)
            .filter(models.EnterpriseClientDocument.client_id == client.id)
            .order_by(models.EnterpriseClientDocument.created_at.desc())
            .all()
        )
        return {
            "client": client.full_name,
            "document_count": len(rows),
            "documents": [
                {
                    "document_type": d.document_type,
                    "file_name": d.original_filename,
                    "uploaded_by": d.uploaded_by_name,
                    "uploaded_on": _iso(d.created_at),
                    "has_readable_text": bool((d.extracted_text or "").strip()),
                }
                for d in rows
            ],
        }

    def read_client_document(name: Optional[str] = None, client_id: Optional[int] = None,
                             document_type: Optional[str] = None) -> dict:
        """Read the extracted TEXT CONTENTS of a client's uploaded document(s) so you can
        answer questions about what's inside them (e.g. passport number/expiry, amounts in
        a bank statement, details in an offer letter). Provide the client's name or
        client_id; optionally pass a document_type (e.g. 'Passport', 'Financial') to narrow
        it down. Only documents whose text has been extracted are returned."""
        client, multi = _resolve_client_row(name, client_id)
        if multi:
            return {"multiple_matches": [_client_brief(c) for c in multi]}
        if not client:
            return {"error": "No matching client found."}
        q = (
            db.query(models.EnterpriseClientDocument)
            .filter(models.EnterpriseClientDocument.client_id == client.id)
        )
        if document_type and document_type.strip():
            q = q.filter(func.lower(models.EnterpriseClientDocument.document_type).like(f"%{document_type.strip().lower()}%"))
        rows = q.order_by(models.EnterpriseClientDocument.created_at.desc()).limit(6).all()
        out = []
        for d in rows:
            txt = (d.extracted_text or "").strip()
            out.append({
                "document_type": d.document_type,
                "file_name": d.original_filename,
                "contents": (txt[:8000] if txt else None),
                "text_available": bool(txt),
            })
        if not out:
            return {"client": client.full_name, "documents": [], "note": "No documents matched."}
        return {"client": client.full_name, "documents": out}

    def list_upcoming_calendar_events(within_days: int = 30, include_done: bool = False) -> dict:
        """List this consultancy's calendar for the near term — use this for any question
        about the schedule, calendar, upcoming events, deadlines, interviews, biometrics,
        appointments, follow-ups, who has something coming up, or what's overdue.

        Includes BOTH team-scheduled events (interviews, appointments, biometrics, document
        deadlines, follow-ups) AND auto-derived client key dates: each active client's
        interview/travel key date, and any client passport expiring in the window. Recently
        overdue items (past ~14 days, not yet done) are included so nothing is missed.
        - within_days: how far ahead to look, 1-180 (default 30).
        - include_done: set true to also include events already marked done.
        """
        try:
            days = max(1, min(int(within_days or 30), 180))
        except Exception:
            days = 30
        today = date.today()
        start = today - timedelta(days=14)   # also surface recently-overdue items
        end = today + timedelta(days=days)

        name_cache: dict = {}

        def _cname(cid):
            if not cid:
                return None
            if cid not in name_cache:
                row = (db.query(models.EnterpriseClient.full_name)
                       .filter(models.EnterpriseClient.id == cid,
                               models.EnterpriseClient.organization_id == organization_id).first())
                name_cache[cid] = row[0] if row else None
            return name_cache[cid]

        events: list = []
        mq = (db.query(models.EnterpriseCalendarEvent)
              .filter(models.EnterpriseCalendarEvent.organization_id == organization_id,
                      models.EnterpriseCalendarEvent.event_date >= start,
                      models.EnterpriseCalendarEvent.event_date <= end))
        if not include_done:
            mq = mq.filter(models.EnterpriseCalendarEvent.is_done.is_(False))
        for ev in mq.order_by(models.EnterpriseCalendarEvent.event_date).all():
            d = ev.event_date
            events.append({
                "date": d.isoformat() if d else None, "time": ev.event_time,
                "title": ev.title, "type": ev.event_type, "client": _cname(ev.client_id),
                "notes": (ev.notes or "")[:200] or None, "done": bool(ev.is_done),
                "overdue": bool(d and d < today and not ev.is_done), "source": "scheduled",
            })
        for c in (db.query(models.EnterpriseClient)
                  .filter(models.EnterpriseClient.organization_id == organization_id,
                          models.EnterpriseClient.target_date.isnot(None),
                          models.EnterpriseClient.target_date >= start,
                          models.EnterpriseClient.target_date <= end,
                          models.EnterpriseClient.status.notin_([catalog.STAGE_APPROVED, catalog.STAGE_REJECTED])).all()):
            d = c.target_date
            events.append({"date": d.isoformat() if d else None, "time": None,
                           "title": f"Key date — {c.full_name}", "type": "client_deadline",
                           "client": c.full_name, "stage": _stage_label(c.status),
                           "overdue": bool(d and d < today), "source": "client_key_date"})
        for c in (db.query(models.EnterpriseClient)
                  .filter(models.EnterpriseClient.organization_id == organization_id,
                          models.EnterpriseClient.passport_expiry.isnot(None),
                          models.EnterpriseClient.passport_expiry >= start,
                          models.EnterpriseClient.passport_expiry <= end).all()):
            d = c.passport_expiry
            events.append({"date": d.isoformat() if d else None, "time": None,
                           "title": f"Passport expiry — {c.full_name}", "type": "passport_expiry",
                           "client": c.full_name, "overdue": bool(d and d < today),
                           "source": "client_key_date"})
        events.sort(key=lambda e: (e["date"] or "", e["time"] or "99:99", e["title"] or ""))
        return {"today": today.isoformat(), "within_days": days,
                "count": len(events), "events": events[:60]}

    return [
        get_portal_overview,
        count_clients,
        search_clients,
        get_client_details,
        clients_needing_attention,
        list_recent_activity,
        get_team_workload,
        list_client_documents,
        read_client_document,
        list_upcoming_calendar_events,
    ]


# ---------------------------------------------------------------------------
# System instruction + chat runner
# ---------------------------------------------------------------------------

def _system_instruction(organization_name: str, user_name: str, role: str) -> str:
    today = datetime.utcnow().strftime("%A, %d %B %Y")
    stages = ", ".join(f"{s['label']} ({s['key']})" for s in catalog.CLIENT_STAGES)
    countries = ", ".join(c["name"] for c in catalog.COUNTRIES)
    return (
        f"You are the Rilono AI Assistant inside the Rilono Enterprise portal for "
        f"the student-visa consultancy \"{organization_name}\". You are helping {user_name} "
        f"(role: {role}).\n\n"
        f"Today is {today} (UTC).\n\n"
        "You help staff understand and act on their own client portal. ALWAYS use the provided "
        "tools to look up real data before answering anything about clients, counts, statuses or "
        "activity — never guess or invent numbers, names or details. If the tools return nothing, "
        "say so plainly.\n\n"
        f"The visa pipeline stages are: {stages}.\n"
        f"This consultancy handles STUDENT visas for these destinations only: {countries}.\n\n"
        "How to answer:\n"
        "- Be genuinely helpful and informative — give a complete, useful answer, never a bare one-liner. "
        "When the data supports it, write a few sentences or a short structured list rather than a single "
        "line, and add the context a busy staff member would actually want.\n"
        "- When the question is about a SPECIFIC client, call get_client_details and summarize who they are: "
        "their visa type and destination, current status, intake, key date, assigned counselor, and the most "
        "recent note if there is one — then suggest a sensible next step for the staff member.\n"
        "- When listing or counting clients, show each client's status plus the detail relevant to the "
        "question, and finish with a short takeaway (e.g. how the pipeline is split, or who is most urgent).\n"
        "- For 'who needs attention' questions, use the attention tool and give the reason for each, most "
        "urgent first.\n"
        "- You can also read the TEXT inside documents staff have uploaded for a client (passports, offer "
        "letters, financial proofs, transcripts, etc.) via the document tools. Use them when asked what a "
        "document says or contains (e.g. a passport number/expiry, or amounts in a bank statement). If a "
        "document's text hasn't been extracted yet, say it isn't available to read.\n"
        "- For anything about the schedule, calendar, upcoming events, deadlines, interviews, biometrics, "
        "appointments, follow-ups or what's overdue, call list_upcoming_calendar_events — it covers both "
        "team-scheduled events and auto-derived client key dates (interview/travel dates, passport expiries). "
        "Lead with what's soonest or overdue, and name the client and date.\n"
        "- Use light formatting for readability: short **bold** labels and tight bullet lists; keep it "
        "skimmable. Don't pad with filler or repeat the question back, and never invent data.\n"
        "- You can read data but cannot make changes; if asked to edit, add, or email a client, say so and "
        "point to the exact screen (e.g. 'open the client and use Send email', or '+ Add Client').\n"
        "- Never reveal data about any other organization; you only have access to this one.\n"
        "- Do not output raw JSON or tool names; answer in clean, friendly natural language.\n"
        "- STRICT SCOPE: only help with this consultancy's portal data and student-visa work. If asked "
        "anything unrelated (general coding, essays, trivia, using you as a general chatbot), decline in one "
        "short sentence and redirect — do not answer it, to conserve resources."
    )


def _convert_history(history: Optional[list]) -> list:
    """Convert [{role, content}] into the genai chat history format."""
    out = []
    if not history:
        return out
    for turn in history[-MAX_HISTORY_TURNS:]:
        role = str((turn or {}).get("role", "")).strip().lower()
        content = str((turn or {}).get("content", "")).strip()
        if not content:
            continue
        genai_role = "model" if role in ("model", "assistant", "ai") else "user"
        out.append({"role": genai_role, "parts": [content]})
    return out


def run_enterprise_ai_chat(
    *,
    db: Session,
    organization: models.EnterpriseOrganization,
    user: models.User,
    role: str,
    message: str,
    history: Optional[list] = None,
) -> str:
    """Run one turn of the enterprise AI assistant. Returns the assistant's text answer."""
    if not is_ai_configured():
        return ("The AI assistant isn't configured yet — an administrator needs to enable "
                "Rilono AI on the server.")

    tools = build_org_tools(db, organization.id)
    system = _system_instruction(
        organization_name=organization.company_name or "your consultancy",
        user_name=(user.full_name or user.email or "there"),
        role=role,
    )

    last_error = None
    for model_name in _enterprise_model_candidates():
        try:
            model = gemini_utils.genai.GenerativeModel(model_name, tools=tools, system_instruction=system)
            chat = model.start_chat(
                history=_convert_history(history),
                enable_automatic_function_calling=True,
            )
            response = chat.send_message((message or "").strip()[:4000])
            ai_usage.record_gemini_usage("enterprise_copilot", model_name, response)
            text = (getattr(response, "text", None) or "").strip()
            if not text:
                return "I couldn't find an answer to that. Try rephrasing, or ask about your clients, statuses or recent activity."
            return sanitize_public_ai_text(text)
        except Exception as exc:  # noqa: BLE001
            last_error = exc
            logger.warning("Enterprise AI model attempt failed (%s)", model_name, exc_info=True)

    raise RuntimeError("Enterprise AI assistant could not answer right now.") from last_error


# ---------------------------------------------------------------------------
# Deep Scan document audit (premium, credit-billed)
# ---------------------------------------------------------------------------

# Deep Scan uses a two-stage map-reduce so it scales to any file size without ever
# silently dropping documents or overflowing the model's context:
#   MAP    — one small call per document extracts its audit facts as structured JSON
#            (each call sees ONE document in full → nothing is truncated or dropped).
#   REDUCE — one call cross-references the compact facts of ALL documents at once
#            (structured input stays tiny even for 40+ docs → sharp, complete audit).
# Per-document extractions are cached on the document row (keyed by a text hash), so
# re-scans only re-run the cheap reduce step.

# Read each document in full up to this cap for the MAP step (a whole passport / bank
# statement / offer letter fits comfortably; guards against pathological OCR blobs).
DEEP_SCAN_EXTRACT_MAX_DOC_CHARS = int(os.getenv("DEEP_SCAN_EXTRACT_MAX_DOC_CHARS", "60000") or "60000")
# Safety cap on how many documents a single scan will process.
DEEP_SCAN_MAX_DOCUMENTS = int(os.getenv("DEEP_SCAN_MAX_DOCUMENTS", "40") or "40")
# The REDUCE step only sees compact structured facts, which stay small even for large
# files; this is a generous guardrail, not a real constraint.
DEEP_SCAN_RECONCILE_MAX_CHARS = int(os.getenv("DEEP_SCAN_RECONCILE_MAX_CHARS", "160000") or "160000")


def _deep_scan_generate(system_instruction: str, prompt: str, usage_source: str, model_state: dict):
    """Generate with enterprise model-candidate FALLBACK (mirrors the copilot loop).

    Deep Scan previously pinned to `_enterprise_model_candidates()[0]` with no fallback, so a
    single dead primary id (e.g. `gemini-3.1-pro` 404ing while only `-preview` is live) made the
    whole feature 502. This tries each candidate in order and remembers the first that works in
    `model_state['ok']`, so later calls in the same scan skip the dead ones. Raises RuntimeError
    only if EVERY candidate fails (caller then 502s without charging credits).
    """
    genai = gemini_utils.genai
    candidates = _enterprise_model_candidates()
    ok = model_state.get("ok")
    if ok:
        candidates = [ok] + [c for c in candidates if c != ok]
    last_error = None
    for model_name in candidates:
        try:
            model = genai.GenerativeModel(model_name, system_instruction=system_instruction)
            response = model.generate_content(prompt)
            model_state["ok"] = model_name
            ai_usage.record_gemini_usage(usage_source, model_name, response)
            return response
        except Exception as exc:
            last_error = exc
            logger.warning("Deep Scan model attempt failed (%s): %s", model_name, exc)
            continue
    raise RuntimeError(f"Deep Scan: all model candidates failed ({last_error})")


def _parse_json_object(text: Optional[str]):
    """Best-effort parse of a JSON object from a model response (tolerates code fences / prose)."""
    s = (text or "").strip()
    if not s:
        return None
    s = re.sub(r"^```(?:json)?\s*", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*```$", "", s).strip()
    try:
        return json.loads(s)
    except Exception:
        pass
    match = re.search(r"\{.*\}", s, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except Exception:
            return None
    return None


def _deep_scan_client_block(client: models.EnterpriseClient) -> str:
    bits = [
        f"Full name: {client.full_name or '—'}",
        f"Destination: {client.destination_country_name or client.destination_country_code or '—'}",
        f"Visa type: {client.visa_type or '—'}",
        f"Intake: {client.intake or '—'}",
        f"Passport number: {client.passport_number or '—'}",
        f"Passport expiry: {_iso(client.passport_expiry) or '—'}",
        f"Date of birth: {_iso(client.date_of_birth) or '—'}",
        f"Nationality: {client.nationality or '—'}",
    ]
    return "\n".join(bits)


_DEEP_SCAN_EXTRACT_SYSTEM = (
    "You are a precise visa-document data extractor. From ONE document's text, extract only the "
    "audit-relevant facts that are ACTUALLY present. Never guess, infer, or invent — use null or [] "
    "when a field is absent. Preserve values exactly as written (names, numbers, dates). "
    "Return STRICT JSON only, with no prose or code fences."
)

_DEEP_SCAN_FACTS_SCHEMA = (
    "{\n"
    '  "document_type": "what this document is (as labeled or clearly evident)",\n'
    '  "person_names": ["every person name as written"],\n'
    '  "date_of_birth": "YYYY-MM-DD or as written, else null",\n'
    '  "passport_number": "or null",\n'
    '  "nationality": "or null",\n'
    '  "issue_date": "or null",\n'
    '  "expiry_date": "or null",\n'
    '  "institution": "school / bank / sponsor / issuer name, or null",\n'
    '  "financials": [{"label": "", "amount": "", "currency": "", "as_of_date": ""}],\n'
    '  "key_dates": [{"label": "", "date": ""}],\n'
    '  "audit_notes": ["anything a visa auditor should know from THIS document only"]\n'
    "}"
)


def _extract_document_facts(doc, model_state: dict):
    """MAP step: extract one document's structured facts as JSON (or None on failure)."""
    text = (getattr(doc, "extracted_text", None) or "").strip()[:DEEP_SCAN_EXTRACT_MAX_DOC_CHARS]
    prompt = (
        f"Return JSON with exactly these keys:\n{_DEEP_SCAN_FACTS_SCHEMA}\n\n"
        f"DOCUMENT TYPE (as labeled by the uploader): {getattr(doc, 'document_type', 'Document')}\n"
        f"DOCUMENT TEXT:\n{text}"
    )
    response = _deep_scan_generate(_DEEP_SCAN_EXTRACT_SYSTEM, prompt, "deep_scan_extract", model_state)
    return _parse_json_object(getattr(response, "text", None))


def _facts_for_document(doc, model_state: dict) -> tuple[Optional[dict], str]:
    """Return (facts, status). Reuses cached extraction when the source text is unchanged."""
    text = (getattr(doc, "extracted_text", None) or "").strip()
    if not text:
        return None, "no_text"
    text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
    if getattr(doc, "deep_scan_facts_hash", None) == text_hash and getattr(doc, "deep_scan_facts", None):
        try:
            return json.loads(doc.deep_scan_facts), "cached"
        except Exception:
            pass
    facts = _extract_document_facts(doc, model_state)
    if not isinstance(facts, dict):
        return None, "extract_failed"
    try:
        doc.deep_scan_facts = json.dumps(facts, ensure_ascii=False)[:200000]
        doc.deep_scan_facts_hash = text_hash
    except Exception:
        pass
    return facts, "extracted"


def run_deep_scan_audit(
    *,
    db: Optional[Session] = None,
    client: models.EnterpriseClient,
    organization: models.EnterpriseOrganization,
    documents: list,
    current_date: Optional[str] = None,
) -> dict:
    """
    Cross-reference a client's uploaded documents with Gemini (map-reduce) to surface
    mismatched dates/names, missing funds and timeline risks before the visa appointment.

    Reads every document in full (no silent truncation), then reconciles the extracted
    facts across the whole file in one pass. Returns:
      {"report": <markdown>, "risk_level": "low|medium|high",
       "documents_analyzed": int, "documents_total": int,
       "documents_skipped": int, "documents_over_cap": int, "extraction_failures": int}
    Raises if the AI isn't configured or no readable documents exist (so the caller can
    avoid charging credits).
    """
    if not is_ai_configured():
        raise RuntimeError("Deep Scan AI is not configured.")

    all_docs = list(documents or [])
    readable = [d for d in all_docs if (getattr(d, "extracted_text", None) or "").strip()]
    if not readable:
        raise ValueError(
            "No readable document text yet. Upload documents (PDF/images) and wait a moment "
            "for text extraction before running a Deep Scan."
        )

    # One resolved-model cache shared across every Gemini call in this scan (map + reduce),
    # so a dead primary id (e.g. gemini-3.1-pro 404) is skipped after the first fallback.
    model_state: dict = {}
    processed = readable[:DEEP_SCAN_MAX_DOCUMENTS]
    over_cap = max(0, len(readable) - len(processed))
    skipped_no_text = len(all_docs) - len(readable)

    # ---- MAP: per-document structured extraction (cached) ----
    # A single document's extraction failing must NOT kill the whole scan — it's counted and
    # the reconcile step still runs on the rest. Only a fully-broken model (every candidate
    # failing, which raises in the reduce step below) 502s the request without charging credits.
    per_doc: list[dict] = []
    extraction_failures = 0
    for idx, doc in enumerate(processed, start=1):
        try:
            facts, status = _facts_for_document(doc, model_state)
        except Exception:
            logger.warning("Deep Scan: extraction failed for doc idx=%s", idx, exc_info=True)
            facts = None
        if not isinstance(facts, dict):
            extraction_failures += 1
            facts = {
                "document_type": getattr(doc, "document_type", "Document"),
                "extraction_failed": True,
                "raw_excerpt": (getattr(doc, "extracted_text", None) or "").strip()[:2000],
            }
        per_doc.append({
            "doc_index": idx,
            "document_type": getattr(doc, "document_type", "Document"),
            "filename": getattr(doc, "original_filename", "file"),
            "facts": facts,
        })

    # Persist freshly-cached extractions (best-effort; independent of the credit charge).
    if db is not None:
        try:
            db.commit()
        except Exception:
            db.rollback()

    # ---- REDUCE: reconcile the compact facts across ALL documents in one pass ----
    eval_date = (current_date or "").strip() or datetime.utcnow().date().isoformat()
    system = (
        "You are a meticulous senior visa-documentation auditor for a study-abroad consultancy. "
        "You are given a CLIENT PROFILE and STRUCTURED FACTS already extracted from each uploaded "
        "document. Cross-reference them to catch errors BEFORE the visa appointment, protecting the "
        "agency's university commission. Be precise, cite the document index for every finding, and "
        "never invent facts that are not present in the provided data."
    )
    facts_json = json.dumps(per_doc, ensure_ascii=False, indent=1)[:DEEP_SCAN_RECONCILE_MAX_CHARS]
    context_text = (
        f"CLIENT PROFILE:\n{_deep_scan_client_block(client)}\n\n"
        f"STRUCTURED DOCUMENT FACTS (JSON array; 'doc_index' identifies each document):\n{facts_json}"
    )
    question = f"""Audit this student's visa file using the CLIENT PROFILE and STRUCTURED DOCUMENT FACTS above. Today's date for evaluation is {eval_date}.

Cross-check across ALL documents and report:
1. Identity consistency — name, date of birth, passport number, nationality must match across documents and the profile.
2. Timeline compliance — bank statements older than 6 months, passport expiring within 6 months of travel, offer/enrolment-confirmation (e.g. I-20, CAS, LOA/PAL, CoE, Zulassungsbescheid)/intake dates already in the past.
3. Financial sufficiency — whether the bank balance / sponsor funds clearly cover tuition + living costs; flag if missing or ambiguous.
4. Missing critical documents for a {client.visa_type or 'student'} visa to {client.destination_country_name or 'the destination'}.

Respond in concise Markdown with these sections:
## Overall Risk
One of: LOW, MEDIUM, or HIGH — on its own line, followed by a one-sentence reason.
## Mismatches & Errors
Bullet list. Cite the document like "(Doc 2)" using its doc_index. If none, say "None found".
## Missing or Stale Documents
Bullet list. If none, say "None".
## Recommended Actions
A short prioritized checklist for the counselor."""

    response = _deep_scan_generate(system, f"{context_text}\n\n{question}", "deep_scan", model_state)
    report = (getattr(response, "text", None) or "").strip()
    if not report:
        raise RuntimeError("The Deep Scan did not return a report. Please try again.")

    upper = report.upper()
    risk_level = "medium"
    head = upper.split("## MISMATCHES")[0]
    if "HIGH" in head:
        risk_level = "high"
    elif "LOW" in head:
        risk_level = "low"

    # Be honest about coverage — never let a counselor assume the whole file was scanned
    # when some documents had no text, were over the cap, or failed to parse.
    coverage_notes = []
    if skipped_no_text:
        coverage_notes.append(f"{skipped_no_text} had no readable text yet and were skipped")
    if over_cap:
        coverage_notes.append(f"{over_cap} beyond the {DEEP_SCAN_MAX_DOCUMENTS}-document limit were not scanned")
    if extraction_failures:
        coverage_notes.append(f"{extraction_failures} could not be fully parsed and were audited from a raw excerpt")
    if coverage_notes:
        report += (
            f"\n\n---\n_Scan coverage: audited {len(processed)} of {len(all_docs)} document(s). "
            + "; ".join(coverage_notes)
            + "._"
        )

    return {
        "report": report,
        "risk_level": risk_level,
        "documents_analyzed": len(processed),
        "documents_total": len(all_docs),
        "documents_skipped": skipped_no_text,
        "documents_over_cap": over_cap,
        "extraction_failures": extraction_failures,
    }
